# Generated by Django 2.1.4 on 2019-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190412_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='m1',
            field=models.CharField(default='10086', max_length=20, verbose_name='队员1联系方式'),
        ),
        migrations.AddField(
            model_name='teams',
            name='m2',
            field=models.CharField(default='10086', max_length=20, verbose_name='队员2联系方式'),
        ),
        migrations.AddField(
            model_name='teams',
            name='m3',
            field=models.CharField(default='10086', max_length=20, verbose_name='队员3联系方式'),
        ),
        migrations.AddField(
            model_name='teams',
            name='m4',
            field=models.CharField(default='10086', max_length=20, verbose_name='队员4联系方式'),
        ),
        migrations.AddField(
            model_name='teams',
            name='m5',
            field=models.CharField(default='10086', max_length=20, verbose_name='队员5联系方式'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='队长邮箱'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/', verbose_name='队伍头像'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='mate1',
            field=models.CharField(default='队员1', max_length=20, verbose_name='队员1'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='mate2',
            field=models.CharField(default='队员2', max_length=20, verbose_name='队员2'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='mate3',
            field=models.CharField(default='队员3', max_length=20, verbose_name='队员3'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='mate4',
            field=models.CharField(default='队员4', max_length=20, verbose_name='队员4'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='mate5',
            field=models.CharField(default='队员5', max_length=20, verbose_name='队员5'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(default='队伍名', max_length=10, verbose_name='队伍名'),
        ),
    ]
