# Generated by Django 2.1.4 on 2019-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='普通会员表',
            name='生日',
            field=models.DateField(blank=True, null=True),
        ),
    ]
