# Generated by Django 2.1.4 on 2019-04-12 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190412_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='date',
        ),
        migrations.AddField(
            model_name='games',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='games',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
    ]
