# Generated by Django 2.1.4 on 2019-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190412_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='score',
            field=models.CharField(default='0:0', max_length=3, verbose_name='比分'),
        ),
        migrations.AddField(
            model_name='games',
            name='zhuxi',
            field=models.CharField(default='主席名', max_length=10, verbose_name='主席'),
        ),
    ]
